base_url: https://www.sec.gov

extend_url: /Archives/edgar/data/

headers:
  Connection: close,
  Accept: application/json, text/javascript, */*;q=0.01,
  X-Requested-With: XMLHttpRequest,
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

cik:
  TSLA: 1318605
  AAPL: 320193
  NVDA: 1045810
  AMZN: 1018724
