random_state: 210

# Target column(s) in the dataset
target_column: target

path:
  raw_data_path: 'data/raw_data/dataset.parquet'
  clean_data_path: 'data/processed_data/dataset.parquet'
  test_data_path: 'data/processed_data/test.parquet'
  feature_score_path: 'data/features/ranked_features.parquet'
  trained_model_path: 'data/model/trained_model.pickle'
  trained_full_model_path: 'data/model/trained_full_model.pickle'
  config_model_path: 'data/model/config_model.yaml'
  best_params_path: 'data/model/best_params.pickle'

log_msg:
  # Data acquisition logs
  load_dataset_start_msg: 'Start - Scraping data'
  load_dataset_end_msg: 'End - Loading Scraping data'
  save_dataset_start_msg: 'Start - Saving the dataset'
  save_dataset_end_msg: 'End - Saving the dataset'
  # Data processing logs
  process_data_start_msg: '-> Start - Processing Data <-'
  process_data_end_msg: '-> End - Processing Data <-'
  split_train_test_start_msg: 'Start - Splitting Data to train and test'
  split_train_test_end_msg: 'End - Splitting Data to train and test'
  save_data_as_parquet_start_msg: 'Start - Saving data as parquet'
  save_data_as_parquet_end_msg: 'End - Saving data as parquet'
  rank_feature_start_msg: 'Start - Ranking features'
  rank_feature_end_msg: 'End - Ranking features'
